export const EXPENSE_KEYWORD_MAP: Record<string, string[]> = {
  "Food & Drinks": [
    "makan",
    "minum",
    "nasi",
    "kopi",
    "coffee",
    "cafe",
    "kafe",
    "resto",
    "restoran",
    "gofood",
    "grabfood",
    "shopeefood",
    "warteg",
    "bakso",
    "mie",
    "ayam",
    "sate",
    "snack",
    "sarapan",
    "lunch",
    "dinner",
    "boba",
    "tea",
    "teh",
    "pizza",
    "burger",
    "jus",
    "juice",
    "roti",
    "bakmi",
    "martabak",
    "seblak",
    "pecel",
    "soto",
    "gorengan",
    "angkringan",
    "padang",
    "fast food",
    "kfc",
    "mcd",
    "starbucks",
    "chatime",
    "kuliner",
    "nasi goreng",
    "nasgor",
    "nasi uduk",
    "nasi padang",
    "nasi kuning",
    "ayam geprek",
    "ayam bakar",
    "ayam goreng",
    "sate ayam",
    "sate kambing",
    "pecel lele",
    "mie ayam",
    "indomie",
    "mie goreng",
    "mie kuah",
    "terang bulan",
    "roti bakar",
    "pisang goreng",
    "tahu bulat",
    "cimol",
    "cilor",
    "batagor",
    "siomay",
    "rawon",
    "gule",
    "gulai",
    "rendang",
    "gado-gado",
    "ketoprak",
    "bubur",
    "bubur ayam",
    "dimsum",
    "ramen",
    "sushi",
    "bento",
    "steak",
    "pasta",
    "spaghetti",
    "hotdog",
    "kebab",
    "sandwich",
    "croissant",
    "waffle",
    "pancake",
    "donat",
    "donut",
    "jco",
    "roti o",
    "rotio",
    "hokben",
    "solaria",
    "dcrepes",
    "mixue",
    "haus",
    "janji jiwa",
    "kopi kenangan",
    "fore",
    "espresso",
    "cappuccino",
    "latte",
    "matcha",
    "es teh",
    "esteh",
    "teh botol",
    "smoothie",
    "cemilan",
    "jajanan",
    "maksi",
    "kantin",
    "dine in",
    "takeaway",
  ],
  Transportation: [
    "bensin",
    "pertalite",
    "pertamax",
    "solar",
    "spbu",
    "ojek",
    "gojek",
    "grab",
    "maxim",
    "indrive",
    "tol",
    "parkir",
    "parking",
    "kereta",
    "krl",
    "mrt",
    "lrt",
    "busway",
    "transjakarta",
    "tj",
    "tiket pesawat",
    "grabride",
    "goride",
    "gocar",
    "grabcar",
    "servis motor",
    "servis mobil",
    "bengkel",
    "oli",
    "tambal ban",
    "cuci motor",
    "cuci mobil",
    "helm",
    "stnk",
    "taxi",
    "taksi",
    "angkot",
    "bbm",
    "pertamax turbo",
    "dexlite",
    "pom bensin",
    "shell",
    "bp akr",
    "vivo",
    "etoll",
    "e-toll",
    "tarif tol",
    "kartu tol",
    "valet",
    "karcis parkir",
    "ojol",
    "mikrotrans",
    "jaklingko",
    "commuter line",
    "kereta api",
    "kai",
    "whoosh",
    "kereta cepat",
    "damri",
    "travel",
    "shuttle",
    "bluebird",
    "ganti oli",
    "isi angin",
    "nitrogen",
    "sparepart",
    "aki motor",
    "aki mobil",
    "kampas rem",
    "pajak motor",
    "pajak mobil",
    "sim",
    "garuda",
    "citilink",
    "lion air",
    "super air jet",
    "batik air",
    "airasia",
    "kapal feri",
    "pelni",
    "tiket kapal",
  ],
  Bills: [
    "listrik",
    "pln",
    "token",
    "pdam",
    "air",
    "wifi",
    "indihome",
    "biznet",
    "first media",
    "myrepublic",
    "telkom",
    "pulsa",
    "paket data",
    "kuota",
    "tagihan",
    "bill",
    "bpjs",
    "pbb",
    "internet",
    "iuran",
    "ipl",
    "kebersihan",
    "keamanan",
    "pajak",
    "gas elpiji",
    "gas lpg",
    "aqua galon",
    "token listrik",
    "tagihan pln",
    "tagihan air",
    "gas pgn",
    "isi ulang galon",
    "le minerale galon",
    "iuran sampah",
    "ipl apartemen",
    "iuran rt",
    "iuran rw",
    "telkomsel",
    "indosat",
    "xl",
    "axis",
    "smartfren",
    "by.u",
    "tri",
    "firstmedia",
    "cbn",
    "oxygen",
    "iconnet",
    "bpjs kesehatan",
    "bpjs ketenagakerjaan",
    "asuransi",
    "premi asuransi",
    "prudential",
    "allianz",
    "manulife",
    "axa",
    "pajak bumi",
    "sppt pbb",
  ],
  Groceries: [
    "sayur",
    "beras",
    "buah",
    "minyak",
    "bumbu",
    "pasar",
    "supermarket",
    "indomaret",
    "alfamart",
    "alfamidi",
    "superindo",
    "hypermart",
    "transmart",
    "daging",
    "telur",
    "ikan",
    "belanja dapur",
    "sembako",
    "sabun cuci",
    "detergen",
    "rinso",
    "molto",
    "lotte mart",
    "hero",
    "farmer market",
    "grand lucky",
    "tukang sayur",
    "warung madura",
    "minyak goreng",
    "gula",
    "garam",
    "daging sapi",
    "daging ayam",
    "udang",
    "cumi",
    "sayuran",
    "bayam",
    "kangkung",
    "wortel",
    "tomat",
    "cabai",
    "cabe",
    "bawang merah",
    "bawang putih",
    "bumbu dapur",
    "kecap",
    "saus",
    "sambal",
    "santan",
    "mentega",
    "keju",
    "apel",
    "pisang",
    "jeruk",
    "semangka",
    "melon",
    "alpukat",
    "sabun cuci piring",
    "mama lemon",
    "sunlight",
    "daia",
    "soklin",
    "pelembut",
    "downy",
    "bayfresh",
    "stella",
    "kamper",
    "plastik sampah",
    "tissue",
    "tisu",
    "sponge",
    "spons cuci",
  ],
  "Health & Personal Care": [
    "obat",
    "dokter",
    "apotek",
    "apotik",
    "kimia farma",
    "halodoc",
    "alodokter",
    "k24",
    "skincare",
    "sabun",
    "sampo",
    "shampoo",
    "salon",
    "potong rambut",
    "barbershop",
    "cukur",
    "vitamin",
    "suplemen",
    "rumah sakit",
    "rs",
    "klinik",
    "puskesmas",
    "periksa",
    "dental",
    "gigi",
    "kosmetik",
    "lotion",
    "makeup",
    "parfum",
    "facial",
    "sunscreen",
    "body wash",
    "deodorant",
    "pasta gigi",
    "sikat gigi",
    "resep dokter",
    "konsul dokter",
    "guardian",
    "watsons",
    "century",
    "laboratorium",
    "tes darah",
    "rontgen",
    "swab",
    "rapid",
    "dokter gigi",
    "tambal gigi",
    "scaling gigi",
    "cabut gigi",
    "kacamata optik",
    "optik melawai",
    "optik seis",
    "softlens",
    "sangobion",
    "enervon c",
    "imboost",
    "panadol",
    "bodrex",
    "paracetamol",
    "tolak angin",
    "antangin",
    "minyak kayu putih",
    "freshcare",
    "salonpas",
    "hansaplast",
    "betadine",
    "perban",
    "facial wash",
    "toner",
    "serum",
    "moisturizer",
    "somethinc",
    "avoskin",
    "scarlett",
    "wardah",
    "emina",
    "kahf",
    "make over",
    "maybelline",
    "lipstik",
    "bedak",
    "cushion",
    "eyeliner",
    "maskara",
    "kondisioner",
    "sabun mandi",
    "body lotion",
    "cologne",
    "pomade",
    "wax rambut",
    "creambath",
    "hair spa",
    "manicure",
    "pedicure",
    "waxing",
    "pijat",
    "massage",
    "reflexology",
    "spa",
  ],
  "Hobby & Entertainment": [
    "nonton",
    "bioskop",
    "cinema",
    "xxi",
    "cgv",
    "cinepolis",
    "game",
    "steam",
    "playstation",
    "ps5",
    "xbox",
    "nintendo",
    "netflix",
    "spotify",
    "youtube",
    "disney",
    "prime",
    "konser",
    "tiket konser",
    "topup",
    "top up",
    "diamond",
    "mlbb",
    "genshin",
    "valorant",
    "main",
    "rekreasi",
    "karaoke",
    "billiard",
    "komik",
    "manga",
    "action figure",
    "tiket bioskop",
    "popcorn",
    "fan meeting",
    "pameran",
    "museum",
    "inul vizta",
    "masterpiece",
    "timezone",
    "funworld",
    "dufan",
    "ancol",
    "taman safari",
    "top up game",
    "mobile legends",
    "pubg",
    "free fire",
    "genshin impact",
    "honkai",
    "steam wallet",
    "ps store",
    "ps plus",
    "nintendo switch",
    "eshop",
    "game pass",
    "gacha",
    "youtube premium",
    "disney hotstar",
    "prime video",
    "hbo go",
    "vidio",
    "wetv",
    "iqiyi",
    "apple music",
    "crunchyroll",
    "webtoon",
    "buku komik",
    "novel",
    "gundam",
    "gunpla",
    "lego",
    "hot wheels",
    "trading card",
    "pokemon card",
    "kpop album",
  ],
  Shopping: [
    "belanja",
    "beli",
    "baju",
    "kaos",
    "kemeja",
    "celana",
    "jeans",
    "sepatu",
    "sandal",
    "tas",
    "ransel",
    "pakaian",
    "jaket",
    "hoodie",
    "lazada",
    "shopee",
    "tokopedia",
    "tiktok shop",
    "zalora",
    "uniqlo",
    "h&m",
    "zara",
    "aksesoris",
    "fashion",
    "jam tangan",
    "kacamata",
    "casing",
    "headset",
    "earphone",
    "gadget",
    "t-shirt",
    "blouse",
    "tunik",
    "gamis",
    "celana panjang",
    "celana pendek",
    "rok",
    "sweater",
    "cardigan",
    "jas",
    "blazer",
    "undergarment",
    "celana dalam",
    "bra",
    "boxer",
    "kaos kaki",
    "sneakers",
    "sepatu kerja",
    "pantofel",
    "heels",
    "backpack",
    "tote bag",
    "sling bag",
    "dompet",
    "wallet",
    "topi",
    "ikat pinggang",
    "gesper",
    "dasi",
    "blibli",
    "pull&bear",
    "bershka",
    "stradivarius",
    "erigo",
    "roughneck",
    "matahari",
    "ramayana",
    "smartwatch",
    "perhiasan",
    "kalung",
    "cincin",
    "gelang",
    "anting",
    "casing hp",
    "tempered glass",
    "charger",
    "kabel data",
    "powerbank",
    "tws",
    "airpods",
    "keyboard",
    "mouse",
    "flashdisk",
  ],
  Education: [
    "spp",
    "kuliah",
    "sekolah",
    "buku",
    "les",
    "kursus",
    "ukt",
    "tuition",
    "course",
    "udemy",
    "coursera",
    "book",
    "modul",
    "semester",
    "ujian",
    "skripsi",
    "wisuda",
    "seminar",
    "workshop",
    "alat tulis",
    "fotocopy",
    "print",
    "uang sekolah",
    "uang gedung",
    "daftar ulang",
    "uang kuliah",
    "biaya semester",
    "toga",
    "sidang",
    "almamater",
    "buku pelajaran",
    "buku paket",
    "lks",
    "modul kuliah",
    "les privat",
    "bimbingan belajar",
    "bimbel",
    "kumon",
    "ef",
    "english first",
    "kursus bahasa",
    "kursus stir mobil",
    "kursus coding",
    "bootcamp",
    "sertifikasi",
    "toefl",
    "ielts",
    "toeic",
    "hsk",
    "skillshare",
    "dicoding",
    "revou",
    "webinar",
    "konferensi",
    "atk",
    "buku tulis",
    "pulpen",
    "pensil",
    "penghapus",
    "tipp-ex",
    "spidol",
    "stabilo",
    "penggaris",
    "map",
    "binder",
    "kertas hvs",
    "print dokumen",
    "jilid",
  ],
  "Family Needs": [
    "popok",
    "susu",
    "pampers",
    "baby",
    "bayi",
    "anak",
    "kebutuhan rumah",
    "keluarga",
    "belanja bulanan keluarga",
    "perabotan",
    "kasur",
    "sprei",
    "alat dapur",
    "mainan anak",
    "mamy poko",
    "sweety",
    "merries",
    "susu formula",
    "morinaga",
    "sgm",
    "dancow",
    "chil kid",
    "bubur bayi",
    "promina",
    "cerelac",
    "baju bayi",
    "botol susu",
    "dot",
    "stroller",
    "lego anak",
    "buku cerita anak",
    "belanja bulanan rumah",
    "sarung bantal",
    "selimut",
    "handuk",
    "keset",
    "sapu",
    "pelan",
    "ember",
    "gantungan baju",
    "rak piring",
    "wajan",
    "panci",
    "spatula",
    "pisau dapur",
    "tupperware",
    "kotak makan",
    "termos",
    "bohlam",
    "lampu kamar",
    "perbaikan rumah",
    "tukang bangunan",
  ],
  "Gift and Charity": [
    "sedekah",
    "infaq",
    "zakat",
    "donasi",
    "kado",
    "hadiah",
    "sumbangan",
    "charity",
    "gift",
    "angpao",
    "kondangan",
    "amplop",
    "traktir",
    "patungan",
    "infak",
    "zakat fitrah",
    "zakat mal",
    "kitabisa",
    "wakaf",
    "santunan anak yatim",
    "celengan masjid",
    "kotak amal",
    "kado ulang tahun",
    "hadiah ultah",
    "kado pernikahan",
    "kado wisuda",
    "kado bayi",
    "amplop kondangan",
    "uang kondangan",
    "hampers",
    "parcel lebaran",
    "parcel natal",
    "buket bunga",
    "traktir teman",
    "patungan makan",
    "sawer",
    "tips pelayan",
    "tip kurir",
    "tip ojol",
  ],
  "Saving & Investment": [
    "tabungan",
    "menabung",
    "saham",
    "reksadana",
    "bibit",
    "ajaib",
    "bareksa",
    "crypto",
    "binance",
    "indodax",
    "tokocrypto",
    "emas",
    "antam",
    "deposit",
    "deposito",
    "save",
    "invest",
    "investasi",
    "btc",
    "rdpu",
    "rdpt",
    "nabung",
    "buka rekening",
    "reksadana saham",
    "ihsg",
    "ipo",
    "beli saham",
    "bitcoin",
    "ethereum",
    "eth",
    "solana",
    "usdt",
    "pintu",
    "pluang",
    "stockbit",
    "emas antam",
    "logam mulia",
    "tabungan emas",
    "pegadaian",
    "p2p lending",
    "sukuk",
    "ori",
    "sbr",
    "sbn",
    "obligasi negara",
  ],
  Loans: [
    "cicilan",
    "pinjaman",
    "kpr",
    "leasing",
    "angsuran",
    "kredit",
    "paylater",
    "spaylater",
    "gopaylater",
    "kredivo",
    "akulaku",
    "pinjol",
    "finmas",
    "ada kami",
    "kredit rumah",
    "cicilan motor",
    "cicilan mobil",
    "fif",
    "adira",
    "oto finance",
    "baf",
    "wom finance",
    "kredit hp",
    "kredit laptop",
    "home credit",
    "megazip",
    "shopee paylater",
    "lazada paylater",
    "indodana",
    "pinjaman online",
  ],
  "Lending & Receivables": [
    "pinjamkan",
    "talangan",
    "piutang",
    "pinjemin",
    "utangin",
    "talangin",
    "pinjaman teman",
    "kasih pinjam",
  ],
  Debt: [
    "bayar utang",
    "lunas utang",
    "bayar hutang",
    "lunas",
    "utang",
    "hutang",
    "pelunasan hutang",
    "bayar cicilan teman",
    "balikin pinjaman",
    "lunasin utang",
  ],
  Sports: [
    "gym",
    "fitness",
    "futsal",
    "badminton",
    "bulutangkis",
    "renang",
    "workout",
    "sewa lapangan",
    "raket",
    "bola",
    "running",
    "lari",
    "jersey",
    "sepatu lari",
    "yoga",
    "pilates",
    "padel",
    "membership gym",
    "celebrity fitness",
    "fitness first",
    "sewa lapangan futsal",
    "sewa lapangan badminton",
    "raket badminton",
    "shuttlecock",
    "kolam renang",
    "tiket renang",
    "tenis",
    "sewa lapangan tenis",
    "padel tennis",
    "golf",
    "driving range",
    "basket",
    "voli",
    "calisthenics",
    "zumba",
    "aerobik",
    "marathon",
    "lari pagi",
    "matras yoga",
    "dumbell",
    "protein whey",
    "creatine",
  ],
  Traveling: [
    "hotel",
    "tiket liburan",
    "villa",
    "tour",
    "staycation",
    "homestay",
    "pantai",
    "wisata",
    "liburan",
    "traveloka",
    "tiket.com",
    "airbnb",
    "paspor",
    "visa",
    "resort",
    "hostel",
    "agoda",
    "booking.com",
    "traveloka hotel",
    "tiket.com hotel",
    "glamping",
    "camping",
    "sewa tenda",
    "tour guide",
    "paket liburan",
    "tempat wisata",
    "tiket masuk wisata",
    "gunung",
    "sewa mobil liburan",
    "sewa motor liburan",
    "bikin paspor",
    "perpanjang paspor",
    "bagasi pesawat",
    "asuransi perjalanan",
  ],
  "Other Expense": [
    "biaya admin",
    "admin bank",
    "transfer",
    "rupa-rupa",
    "lain-lain",
    "denda",
    "materai",
    "biaya transfer",
    "biaya tarik tunai",
    "biaya top up",
    "denda tilang",
    "meterai",
    "fotocopy ktp",
    "legalisir",
    "biaya notaris",
    "ongkir",
    "ongkos kirim",
  ],
};
