export const INCOME_KEYWORD_MAP: Record<string, string[]> = {
  Salary: [
    "gaji",
    "payroll",
    "salary",
    "upah",
    "gajian",
    "thr",
    "tunjangan",
    "honor",
    "honorarium",
    "gaji bulanan",
    "gaji pokok",
    "tunjangan makan",
    "tunjangan transport",
    "tunjangan jabatan",
    "tunjangan hari raya",
    "gaji ke-13",
    "uang makan kantor",
    "uang saku kantor",
  ],
  "Business & Profit": [
    "omset",
    "omzet",
    "jualan",
    "usaha",
    "toko",
    "dagang",
    "laba",
    "keuntungan",
    "orderan",
    "profit",
    "sales",
    "penjualan",
    "pelanggan",
    "customer",
    "invoice",
    "proyek bisnis",
    "hasil jualan",
    "keuntungan jualan",
    "orderan masuk",
    "closing",
    "invoice dibayar",
    "penjualan toko",
    "dagangan",
    "hasil panen",
    "hasil ternak",
    "toko online",
    "pesanan pelanggan",
    "omzet harian",
    "omzet bulanan",
  ],
  "Freelance & Side Job": [
    "freelance",
    "side job",
    "side income",
    "project",
    "proyek",
    "tip",
    "fee",
    "komisi jasa",
    "desain",
    "ngoding",
    "jasa",
    "konsultasi",
    "bikin web",
    "editing",
    "fotografi",
    "side hustle",
    "penghasilan sampingan",
    "fee proyek",
    "uang proyek",
    "project fee",
    "fee desain",
    "fee ngoding",
    "jasa pembuatan",
    "jasa foto",
    "jasa video",
    "honor mc",
    "fee narasumber",
    "fee pembicara",
    "jasa servis",
    "jasa konsultasi",
    "tip customer",
    "tips ojol",
    "upah lemburan freelance",
  ],
  "Bonus & Commission": [
    "bonus",
    "insentif",
    "komisi",
    "reward",
    "bonus tahunan",
    "insentif lembur",
    "lemburan",
    "hadiah lomba",
    "juara",
    "bounty",
    "bonus performa",
    "bonus target",
    "bonus kpi",
    "komisi penjualan",
    "komisi affiliate",
    "affiliate shopee",
    "affiliate tiktok",
    "komisi sales",
    "hadiah giveaway",
    "uang lembur",
  ],
  "Investment & Dividend": [
    "dividen",
    "dividend",
    "return",
    "bunga bank",
    "bunga",
    "capital gain",
    "profit saham",
    "profit crypto",
    "bagi hasil",
    "royalti",
    "kupon obligasi",
    "sbn",
    "gain saham",
    "cuan saham",
    "cuan crypto",
    "bunga deposito",
    "bunga tabungan",
    "kupon sukuk",
    "kupon sbr",
    "kupon ori",
    "hasil reksadana",
    "royalti buku",
    "royalti lagu",
    "passive income",
  ],
  "Allowance & Gift": [
    "uang jajan",
    "transfer ortu",
    "dikasih",
    "kado",
    "angpao",
    "hadiah",
    "pemberian",
    "dari papa",
    "dari mama",
    "dari orang tua",
    "kiriman ortu",
    "hibah",
    "uang saku",
    "transferan ortu",
    "kiriman orang tua",
    "dari ayah",
    "dari ibu",
    "dari suami",
    "dari istri",
    "dikasih uang",
    "hadiah uang",
    "angpao imlek",
    "salam tempel",
    "kado uang",
    "warisan",
  ],
  "Rental Income": [
    "sewa kos",
    "uang kos",
    "kost",
    "kontrakan",
    "sewa mobil",
    "sewa rumah",
    "rental",
    "sewa properti",
    "sewa ruko",
    "sewa lapak",
    "kost bulanan",
    "uang kontrakan",
    "sewa kontrakan",
    "sewa apartemen",
    "rental mobil",
    "sewa kamera",
    "sewa alat",
    "pendapatan sewa",
  ],
  "Refund & Cashback": [
    "cashback",
    "refund",
    "pengembalian",
    "poin",
    "promo",
    "voucher balik",
    "kembalian",
    "cashback gopay",
    "cashback ovo",
    "cashback shopee",
    "cashback tokopedia",
    "refund tiket",
    "refund shopee",
    "refund tokopedia",
    "pengembalian dana",
    "voucher cashback",
    "kembalian lebih",
    "klaim asuransi",
    "reimburse",
    "reimbursement kantor",
  ],
  "Debt Repayment": [
    "bayar utang teman",
    "balikin uang",
    "dibayar",
    "pelunasan utang",
    "piutang balik",
    "dibalikin",
    "kembalian utang",
    "pelunasan utang teman",
    "uang kembali",
    "balikin pinjaman",
    "teman lunasin utang",
    "piutang cair",
    "piutang dibayar",
    "kembalian talangan",
  ],
  "Other Income": [
    "temuan",
    "rezeki",
    "rejeki",
    "pemasukan lain",
    "income lain",
    "klaim",
    "rejeki nomplok",
    "nemu uang",
    "sumber lain",
  ],
};
